<a href="https://colab.research.google.com/github/oscarperdomop/HOY/blob/main/Copia_de_numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [ ]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.





In [ ]:
arr = np.array([7,8,4,5,1,2])
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
arr = np.array([7,8,4,5,1,2])
print(arr[:5])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
arr = np.array([7,8,4,5,1,2])
print(arr[:4])

[7 8 4 5]


Reshape the array into a 3 rows and 2 cols (3,2).



In [ ]:
arr = np.array([7,8,4,5,1,2])
newarr = arr.reshape(3, 2)
print(newarr)

[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [ ]:
arr = np.array([7,8,4,5,1,2])
for elemento in arr:
  print(elemento)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [ ]:
nuevos = [0,6,9]
arr2 = np.array(nuevos)
print(arr2)

[0 6 9]


Join the two arrays.



In [ ]:
arr3 = np.concatenate((arr, arr2))

print(arr3)


[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [ ]:
impares = arr3 [arr3 %2!=0]
print("Numero impares",impares)

Numero impares [7 5 1 9]


Sort the joined array elements.



In [ ]:
ordenados = np.sort(arr3)
print("Numero impares",ordenados)

Numero impares [0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
meses = np.array(["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"])
print(meses)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']


Split the months array in 4 periods of 3 elements each one.



In [ ]:
mesplit = np.array_split(meses, 4)
print(mesplit)

[array(['Enero', 'Febrero', 'Marzo'], dtype='<U10'), array(['Abril', 'Mayo', 'Junio'], dtype='<U10'), array(['Julio', 'Agosto', 'Septiembre'], dtype='<U10'), array(['Octubre', 'Noviembre', 'Diciembre'], dtype='<U10')]


Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
letras = np.array(['F','M','F','F','M','F'])
print(letras)

['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [ ]:
busqueda = np.where(letras =='F')[0]
print(busqueda)

[0 2 3 5]


Store in an array the age information [18,20,19,23,19,20].



In [ ]:
edad = np.array([18,20,19,23,19,20])
print(edad)

[18 20 19 23 19 20]


Create a filter array with values < 20.



In [ ]:
filtro = edad <20
print(filtro)

[ True False  True False  True False]


Change the 3 index element with a value of 22



In [ ]:
edad = np.array([18,20,19,23,19,20])
edad[3]=22
print(edad)

[18 20 19 22 19 20]


Print the 4 index element.

In [ ]:
print(edad[3])

22


- OSCAR EUDARDO PERDOMO SAAVEDRA 20192184281
- JUAN ESTEBAN ESCOBAR 20202193890